# File paths
- data:
    rawFilePath:    data/raw/
    intFilePath:    data/interim/
    proFilePath:    data/processed/
    extFilePath:    data/external/
    outPath:        output/
    outPathScratch: scratch/

# PDB data
- pdb:
    rawFilePath:     pdb/raw/
    intFilePath:     pdb/interim/
    proFilePath:     pdb/proccessed/
    extFilePath:     pdb/external/
    codeList:
      - 1a2b
      - 3c4d   

- viz:
    xtick.labelsize: 20
    ytick.labelsize: 20
    font.size: 20
    figure.autolayout: False
    figure.figsize: 12,6
    figure.dpi: 300
    axes.titlesize : 22
    axes.labelsize : 20
    lines.linewidth : 2
    lines.markersize : 6
    legend.fontsize: 16
    mathtext.fontset: stix
    font.family : STIXGeneral
    legend.frameon : False

- colourblind:
    rgb:
        black: 0,0,0
        orange: 230,159,0
        sky_blue: 86,180,233
        bluish_green: 0,158,115
        yellow: 240,228,66
        blue: 0,114,178
        vermillion: 213,94,0
        reddish_purple: 204,121,167
    hex:
        black: \#000000
        orange: \#e69f00
        sky_blue: \#56b4e9
        bluish_green: \#009e73
        yellow: \#f0e442
        blue: \#0072b2
        vermillion: \#d55e00
        reddish_purple: \#cc79a7        

# Reference
# Wong, B., 2011. Points of view: Color blindness.
